apiVersion: apps/v1
kind: Deployment
metadata:
  name: project5-deployment
  labels:
    app: project5-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project5-service
  template:
    metadata:
      labels:
        app: project5-service
    spec:
      containers:
      - name: web
        image: $AWS_ECR/project5:latest
        ports:
          - name: web
            containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: service
spec:
  selector:
    app: project5-service
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000